### PR TITLE
Fix bug when set agent for needle & add test cases

### PR DESCRIPTION
**Pull request by taina0407**
Using deepmerge make agent object invalid with node http, using lodash will avoid this issue.
Also added test case for using agent

### CODE REVIEW

**Comment by puzrin** [comment]
I would not like switch to `lodash.merge`. Could you explain details about problem?

**Comment by taina0407** [comment]
> I would not like switch to `lodash.merge`. Could you explain details about problem (and minimal example how to replroduce)?

As I comment above, because the "agent" configuration instance will be convert to pure object when using deepmerge library, that will cause the needle plugin to fail when using agent (for example to keep alive TCP connection)

Here is the simple code for procedure this error:

```javascript
const http = require("http");
const https = require("https");
const Probe = require("probe-image-size");

(async () => {
  try {
    await Probe("http://via.placeholder.com/350x150", {
      agent: new http.Agent({
        keepAlive: true,
      }),
    });
  } catch (error) {
    console.error(error);
  }

  try {
    await Probe("https://via.placeholder.com/350x150", {
      agent: new https.Agent({
        keepAlive: true,
      }),
    });
  } catch (error) {
    console.error(error);
  }
})();
```

**Comment by puzrin** [comment]
Got it. Seems `deepmerge` has desired changes in upcoming 5.x, but development is not active and we can't wait without deadlines.

Let's accept your proposal, and [may be] roll back later. Thanks for your efforts!

**Comment by puzrin** [comment]
Published 7.1.0

**Pull request merged**
