### PR TITLE
Don't use any-promise

### PR DESCRIPTION
**Pull request by vaskevich**
Don't think there's a reason to use this nowadays. Even https://github.com/kevinbeaty/any-promise says to use native promises.

Sending this out because I got this error in Mocha:
```
Error: global leak detected: '@@any-promise/REGISTRATION'
```

### CODE REVIEW

**Comment by puzrin** [comment]
I have no principal objections, but this requires major version bump. Worth to fix pending bug first. Should happen in 1-2 weeks.

**Comment by puzrin** [comment]
Fixed pending issues. Kick me after 2-4 weeks. Need feedback - is `request` with last changes stable or we should try upgrade to `got` again (this change is breaking too).

**Comment by sayem314** [comment]
Please fix conflicts and merge

**Comment by sayem314** [comment]
@puzrin I see you dropped any-promise. Also, publish this new version to npm maybe?

**Pull request closed without merging**
